import { Link } from "react-router-dom";
import './Agreement.scss';

export default function Agreement() {

  return (
    <div className="agreement-page">
      <h1>Client Agreement</h1>
      <div className="markdown offset-top-lg-s">
        <p>Dolphin Corp LLC (a company incorporated under the laws of Saint Vincent and the Grenadines, registration number 915 LLC 2021, with an office at Euro House, Richmond Hill Road, Kingstown, St.Vincent and the Grenadines, hereinafter — the Company), according to the terms and conditions of this Client Agreement (hereinafter — the Agreement), provides an individual (hereinafter — the Client) with access to the site quarax.com (hereinafter — the Website) and the Quarax mobile application (hereinafter — the Mobile Application) for the purpose of the Client concluding trading operations using financial instruments provided by the Company.</p>
        <p>Pollack Trade LTD (a company registered in accordance with the legislation of the Republic of Bulgaria, whose office is located at Georgi Sava Rakovski St. 96, Sredets Region, Sofia Municipality, Sofia 1000) is an agent of the Company and is part of the Quarax group of companies.</p>
        <p>Unless otherwise specifically stated in this Agreement, all services provided by the Company through the Website are also provided through the Mobile Application.</p>
        <p>1. General Provisions</p>
        <p>1.1. The Client accepts the Agreement by registering and creating an Account on the Website. Acceptance of the Agreement means full and unconditional agreement of the Client to its terms and conditions.</p>
        <p>1.2. The place of supply of services is Saint Vincent and the Grenadines.</p>
        <p>1.3. The <Link to="/privacy">Privacy Policy</Link> and the Cookie Policy published on the Website are integral parts of this Agreement.</p>
        <p>2. Terminology</p>
        <p>2.1. Account&nbsp;is the Client's account on the Website, necessary for authentication and the provision of access to their Personal Account.</p>
        <p>2.2. Asset&nbsp;is stock indices, stocks, commodities, and currency pairs available for trading using financial instruments provided by the Company.</p>
        <p>2.3. Account Balance&nbsp;is the total amount of funds in the Client's Account, excluding Open Trades. The amount of the Account Balance is the amount of the Company's financial obligation to the Client at a particular point in time unless otherwise specified.</p>
        <p>2.4 Risk-free Trade&nbsp;is a Trade that is concluded by the Client at the expense of the Company. The Client has the right to dispose of the profit received as a result of such a Trade at their own discretion and without any restrictions. Risk-free Trades are not a financial obligation of the Company to the Client.</p>
        <p>2.5. Bonuses, Bonus Funds&nbsp;are funds credited by the Company to the Client's Account to increase their trading potential. Bonuses are not a financial obligation of the Company to the Client.</p>
        <p>2.6. Withdrawal of Funds&nbsp;is the debiting of monetary funds from the Account and transfer thereof to the Client's account.</p>
        <p>2.7. A&nbsp;Demo Account&nbsp;is a virtual account for the Client on the Trading Platform, reflecting in real time the results of their Trading Operations on that account. The currency of the Demo Account always matches the currency of the Client's Real Account. Demo Account funds are not a financial obligation of the Company to the Client.</p>
        <p>2.8. Deposit&nbsp;is monetary funds deposited by the Client in their Account.</p>
        <p>2.9. Closed Trade&nbsp;is a Trade in which the Expiration has been reached, or a Trade closed by order of the Client.</p>
        <p>2.10. Quote&nbsp;is the digital cost value of an Asset at a certain point in time.</p>
        <p>2.11. The&nbsp;Client’s Personal Account&nbsp;is a section of the Website with restricted access through which the Client, having completed the authorization procedure by entering their login and password, is able to use the services of the Company.</p>
        <p>2.12. Log File&nbsp;is a file containing system information about the operation of the Company Server and information about the Client’s actions on the Website.</p>
        <p>2.13. A Multiplier&nbsp;is the ratio of Trade Volume to the amount of the Client's investment in a Trade, assigned by them when opening the Trade in the CFD trading mechanics. A Multiplier cannot be more than 10.</p>
        <p>2.14. Non-trading Operation&nbsp;is an operation involving making a Deposit into the Account or Withdrawing Funds from the Client's Account, as well as other operations that are not considered Trading.</p>
        <p>2.15. Trade Volume&nbsp;is the product of the Client's investment in a Trade and the Multiplier assigned by them.</p>
        <p>2.16. Open Trade&nbsp;is a Trade prior to its Expiration or a Trade prior to its closing by order of the Client.</p>
        <p>2.17. Payment System Provider&nbsp;is a company that provides online services for conducting electronic payments.</p>
        <p>2.18. A Client’s Real Account (Client Account, Account)&nbsp;is a special Client Account on the Trading Platform that reflects in real time the results of their Non-trading Operations, Open and Closed Trades, as well as other changes in the Company's financial obligations to the Client. Possible Account Currencies: US dollar, euro.</p>
        <p>2.19. Trade&nbsp;is opposite Trading Operations with the same identification number.</p>
        <p>2.20. The Company Server&nbsp;is a software and hardware complex that provides streams of Quotes to the Client in real time and processes the Client's Trading Orders.</p>
        <p>2.21. Trading Activity&nbsp;is the Client’s actions involving making a Deposit into their Account, Withdrawing Funds, concluding Trading Operations, paid registration for a Tournament, crediting the balance of the Client’s tournament account (re-buys), and activating Bonuses or gifts.</p>
        <p>2.22. Trading Operation&nbsp;is an over-the-counter operation with an Asset concluded between the Company and the Client in a cash settled mode.</p>
        <p>2.23. Trading Platform&nbsp;is a computer system that is accessed through the Client’s Personal Account and is used to display Quote streams transmitted from the Company Server, to place the Client’s Trading Orders, to reflect the results of their execution, and to perform other actions related to the execution of Trading Operations.</p>
        <p>2.24. Trading Order&nbsp;is the Client's order to conclude a Trading Operation on the conditions specified in that order.</p>
        <p>2.25. Trading Mechanics&nbsp;are financial instrument derivatives of Assets provided by the Company on the Trading Platform, the usage of which does not result in the actual acquisition of the Asset.</p>
        <p>2.26. Trading Turnover&nbsp;is the sum of all the Client's investments in Trades made by the Client since the last Deposit was made to the Account.</p>
        <p>2.27. A Tournament&nbsp;is a limited-time competition within the Trading Platform with a monetary prize fund.</p>
        <p>2.28. Expiration&nbsp;is the time of execution of a Trade upon reaching the time of its closing.</p>
        <p>3. Trading Mechanics</p>
        <p>The following Trading Mechanics are available to the Client:</p>
        <p>3.1. Fixed Time Trades (FTT)</p>
        <p>3.1.1. When opening a Trade, the Client indicates the Asset, the amount of the Client's investment in the Trade, the direction of chart movement, and the time of closing of the Trade.</p>
        <p>3.1.2. The Trade closes upon reaching the selected closing time.</p>
        <p>3.1.3. If at the moment of closing of the Trade, the current Quote of the selected Asset is higher than its Quote at the moment of the opening of the Trade, the Trade is considered profitable if the selected direction of chart movement is "up." If at the moment of closing of the Trade, the current Quote of the selected Asset is lower than its Quote at the moment of the opening of the Trade, the Trade is considered profitable if the selected direction of chart movement is "down."</p>
        <p>3.1.4. The Profitability of a Trade is fixed and dependent on the selected amount of the Client's investment in the Trade, the Asset, and the time of execution of the Trade. Earnings on a Trade are defined as the percentage of profitability multiplied by the amount of the Client's investment in the Trade.</p>
        <p>3.2. CFD</p>
        <p>3.2.1. The CFD mechanics are available only on Demo Accounts.</p>
        <p>3.2.2. When opening a Trade, the Client indicates the Asset, the amount of the Client's investment in the Trade, the Multiplier, and the direction of chart movement.</p>
        <p>3.2.3. Trading period: Monday 07:00 UTC to Friday 21:00 UTC. Outside the specified period, conducting of Trading Operations, including opening new and closing current Trades, is not available using the CFD mechanics. If holidays (non-working days) fall during the specified period on the Asset exchange, Trading Operations with that Asset are not conducted on the Trading Platform.</p>
        <p>3.2.4. Earnings on a Trade are calculated using the following formula: Amount of the Client's investment in the Trade x the Multiplier x (closing Quote / opening Quote - 1).</p>
        <p>3.2.5. At the time of opening a Trade, a commission in the amount of 0.02% of the Trade Volume is debited from the Client's Demo Account. When calculating the amount of the commission, it is always rounded up to the nearest tenth in the Demo Account currency.</p>
        <p>3.2.6. When using the CFD mechanics, the Client can have no more than 15 (Fifteen) Trades open at the same time.</p>
        <p>3.2.7. The Trade is closed by order of the Client or automatically.</p>
        <p>A Trade is closed automatically:</p>
        <p>—in the event of a negative financial result for the Trade before its closing reaching 95% of the amount of the Client's investment in the Trade (technical Stop Loss);</p>
        <p>—after 15 (Fifteen) days from the time of opening the Trade.</p>
        <p>3.2.8. If the automatic closing of a Trade (clause 3.2.7) falls during a time when execution of Trading Operations in the CFD mechanics for the Asset of the Trade is not being implemented on the Trading Platform, the Trade is closed immediately after the Quote of the Asset of the Trade is received on the Trading Platform during the next trading period.</p>
        <p>3.2.9. If at the time of closing of the Trade, the current Quote of the selected Asset is higher than its Quote at the time of opening of the Trade, the Trade is considered profitable if the selected direction of the Trade is “up.” If at the time of closing of the Trade, the current Quote of the selected Asset is lower than its Quote at the time of opening of the Trade, the Trade is considered profitable if the selected direction of the Trade is "down."</p>
        <p>3.2.10. The Loss on a Trade when using the CFD mechanics cannot exceed 100% of the amount of the Client's investment in the Trade.</p>
        <p>4. Registration and Verification of the Client</p>
        <p>4.1. The registration procedure is mandatory for the Client.</p>
        <p>4.2. To register on the Website, the Client must perform the following actions:</p>
        <p>- enter their email address and create a password;</p>
        <p>- select the currency of the Account;</p>
        <p>- accept the terms and conditions of this Agreement.</p>The Client can also register on the Website using their Google or Facebook account. In this case, after authorization, the Client must select the currency of the Account and accept the terms and conditions of this Agreement.<br /><br />
        <p>4.3. By accepting the terms and conditions of this Agreement, the Client guarantees the following:</p>
        <p>- that they are a legally capable adult;</p>
        <p>- that they have read the terms of this Agreement and agree to them.</p>
        <p>4.4. In order to ensure the legality and security of the provision of services, the Company conducts a procedure for verifying the identity of the Client and the information indicated by them (verification). In doing this, the Company has the right to request that the Client provide a photograph of:</p>
        <p>- the spread (page) of the Client's passport with his or her photograph and personal data; or</p>
        <p>- the front and back of the Client's ID card; or</p>
        <p>- the Client's driver's license.</p>
        <p>The Company also has the right to request the Client’s current utility bills, bank statements showing the opening of their account, scanned copies of their bank cards, or other documents if the documents provided to them earlier do not allow the Client to be fully identified and/or verify his payment details and confirm the information specified by them.</p>
        <p>4.5. Verification is carried out within 20 (Twenty) minutes from the moment the Client provides the full set of documents requested by the Company. In some cases, the Company has the right to extend this period to 7 (Seven) calendar days.</p>
        <p>4.6. If the Client unjustifiably refuses to provide the documents and/or information requested for verification, the Company has the right to suspend the servicing of their Account and Real Account with subsequent blocking. The Company may return any funds deposited by the Client concerned only by using payment details provided during registration or may withhold such funds until the Client completes verification.</p>
        <p>4.7. To confirm the identity of the Client and verify the documents provided by them, the Company has the right to request &nbsp;a video conference with the Client. In this case, the Client needs to add the Company (support.quarax) to their Skype account and have ready their passport and the bank cards they used when depositing into their Account before the video conference begins. The Client shall be notified about the time of the video conference at least 24 (twenty four) hours prior.</p>
        <p>4.8. By registering on the Website, the Client consents to receiving emails from the Company, including advertising messages, as well as phone calls and SMS texts. If the Client does not want to receive information from the Company by email, they may at any time cancel their subscription by clicking on the "Unsubscribe" link in any email from the Company, by deactivating the corresponding option in their Personal Account, or by contacting the Company's Support Service. The Client may unsubscribe from calls and text messages from the Company at any time by contacting the Company's Support Service. The Company undertakes to immediately respond to the Client’s request to cancel their subscription to all types of emails (except for transactional notifications), as well as not to receive calls or SMS texts.</p>
        <p>4.9. The Client has the right to register only 1 (One) Account on the Website. If the Company discovers several Accounts belonging to the same Client or group of persons, if such persons have the opportunity to log in from the same IP address and/or access the Website from the same device, or credited using the same credit card and/or electronic wallet, or with authorization from the same IP address or upon the detection of other signs of the possession of multiple Accounts, the Trades and their financial outcomes on all such Accounts may be rescinded, and the Accounts may be blocked. In this case, the funds held in those Accounts cannot be considered a financial liability of the Company to the Client. The Company may ask the Client to identify the main Account that the Client wishes to keep. In this event, Deposit funds that the Client has added to other Accounts will be returned by using payment details provided during the registration of such Accounts without (any compensation for) any profits and/or losses.</p>
        <p>4.10. If there has been no Trading Activity on the Client's Account for 90 (Ninety) consecutive days, the Client is charged a non-refundable monthly subscription fee for servicing their Account in the amount of $30/€30 or in an amount equivalent to $30 (depending on the currency of the Account), but no more than the amount of the Account Balance or the funds debited from the Client's Account in the manner specified in clause 4.11 of this Agreement. The subscription fee is canceled from the time whenin the event that Trading Activity is resumed on the Client's Account.</p>
        <p>4.11. If there has been no Trading Activity on the Client's Account for 6 (Six) consecutive months, the Company has the right to debit the funds from the Client's Account in full. In this case, the subscription fee continues to be paid from such debited funds.</p>4.12. In order to return funds to the Account, the Client should contact the Company's Client Support Service using the contact details provided in section 12 of this Agreement. In this case, funds, excluding the subscription fee debited according to clause 4.10 of this Agreement, are returned to the Client's Account.<br /><br /><p>5. Procedure for Conducting Non-trading Operations</p>
        <p>5.1. The official methods of Account crediting and Withdrawal of Funds are the methods indicated on the Company's Website. The Client assumes all the risks associated with the use of payment systems, as well as payment of commissions of payment systems and/or payment system Providers for making payments and/or currency conversion.</p>
        <p>Should the Client credit their Account using a currency other than the Account currency, the Deposit amount credited to the Account shall be determined by the exchange rate set by the Payment System Provider.</p>
        <p>Based on the Client's country, the Client's country of residence, payment method, and/or type of operation, the Company has the right to charge a deposit and/or withdrawal fee. The fee rates are stated below.</p><table><tbody><tr><td><p>Type of operation</p></td><td><p>Payment method</p></td><td><p>Country</p></td><td><p>Fee rate</p></td><td><p>Conditions</p></td></tr><tr><td><p>&nbsp;Withdrawal</p></td><td><p>All methods</p></td><td><p>India, Vietnam</p></td><td><p>10%</p></td><td><p>For all withdrawal requests above the limit of 1 within 24 hours</p></td></tr><tr><td><p>&nbsp;Withdrawal</p></td><td><p>&nbsp;All methods</p></td><td><p>Indonesia</p></td><td><p>&nbsp;2%</p></td><td><p>For all withdrawal requests above the limit of 1 within 24 hours</p></td></tr></tbody></table><p>&nbsp;</p>
        <p>The Company is not responsible for the delay or failure to make a payment from the Account or to the Client's Account due to the fault of the payment system and/or the payment system Provider. In the case of claims regarding the operation of any payment system and/or payment system Provider on the part of the Client, they should contact the support service of that payment system and/or Provider accordingly. The Client is obliged to notify the Company of any cases of such complaints.</p>
        <p>5.2. To credit the Account, the Client uses the internal interface of the Website. The minimum Deposit amount is $10/€10 or an equivalent of $10 (depending on the currency of the Account). At the discretion of the Company, the minimum Deposit amount may be reduced in certain countries. The exact amount of the minimum Deposit is displayed in the Cashier section in the Client’s Personal Account on the Website when crediting their Account. In addition, the size of the minimum Deposit may be reduced as part of promotions or other activities held by the Company.</p>
        <p>5.3. Crediting of an Account using the payment details of third parties is prohibited.</p>
        <p>5.4. In the event that signs of fraud are detected in the conducting of financial transactions after the crediting of funds to the Client’s Account, the Company reserves the right to cancel such transactions and block the Client’s Account.</p>
        <p>5.5. For the Withdrawal of Funds from an Account, the Client creates a corresponding request using the internal interface of the Website. The minimum Withdrawal amount is $10/€10 or an equivalent of $10 (depending on the currency of the Account). At the discretion of the Company, the minimum Withdrawal amount may be reduced in certain countries.</p>
        <p>5.6. After the creation of the request, the amount of funds to be withdrawn is not debited from the Client's Account until the exact moment the payment is made. Payments made at the request of the Client are non-refundable.</p>
        <p>5.7. The Client is solely responsible for the accuracy and reliability of the data entered in their Withdrawal request.</p>
        <p>5.8. A Client’s request for Withdrawal of funds is processed by the Company within 3 (Three) business days following the day of filing such a request. The moment of receipt of funds by the Client depends on the speed of transaction processing by the payment system and/or the Provider of the payment system. The following limits apply to the Withdrawal of funds on the Site: no more than $3,000/€3,000, or an amount equivalent to $3,000 (depending on the Account currency), per day; no more than $10,000/€10,000, or an amount equivalent to $10,000 (depending on the Account currency), before the end of the current week; no more than $40,000/€40,000, or an amount equivalent to $40,000 (depending on the Account currency), before the end of the current month. These limits may be reduced in connection with the particular features of individual withdrawal methods. The Client can learn the exact limits for the Withdrawal of funds for each Withdrawal method from the Company's Client Support Service using the contact information specified in section 12 of this Agreement.</p>
        <p>5.9. After giving prior notice, a Client’s request for the Withdrawal of Funds may be withheld by the Company's security service without execution for up to 10 (Ten) business days.</p>
        <p>5.10. Withdrawals from the Client's Account are carried out in the same manner and using the same account that was used by the Client when crediting their Account. If for technical reasons this is not possible, the Client has the right to use another method and/or other account for the Withdrawal of Funds. In this case, the Client's data for that account must coincide with the data the Client specified during verification. The Company has the right to request proof from the Client to confirm the impossibility of the Withdrawal of Funds using the method and account that were used to credit the Account.</p>
        <p>5.11. In order to comply with international legislation on countering money laundering (Anti-Money Laundering, AML), when Withdrawing Funds from an Account, the Company has the right to request from the Client confirmation that the account to which the Withdrawal is being made belongs to the Client, as well as notarized and, if necessary, apostilled/legalized copies of documents proving the identity, place of residence, and place of registration of the Client. In the event of unjustifiable refusal of the Client to provide these documents, the Company is entitled to decline the Withdrawal of Funds.</p>
        <p>5.12. If the Client clearly intends to use their Account for exchange transactions between payment systems, the Company has the right to decline the Client's request for Withdrawal of Funds from their Account.</p>
        <p>5.13. If the Client deposits funds into their Account and subsequently decides to withdraw them in full or in part, while their Trading Turnover has not yet exceeded double the Deposit amount, the Withdrawal fee will be 10% (Ten percent) of the Account Balance or the Client’s last Deposit, depending on which figure is greater.</p>
        <p>5.14. The Company shall not be liable for the actions of third parties engaged in intermediary activities when the Client conducts operations to credit and/or Withdraw funds from the Client's Account.</p>
        <p>5.15. When the Client conducts operations to credit their Account, the Company's financial responsibility starts when the Client's funds are received in the Company's bank account and/or in the Company’s account in the payment systems indicated on the Website.</p>
        <p>5.16. When the Client conducts operations to Withdraw Funds, the Company's financial responsibility ceases when the funds are withdrawn from the Company's bank account and/or from the Company's account in the payment systems indicated on the Website.</p>
        <p>5.17. In the event of technical errors on the part of the Company when completing financial transactions, the Company reserves the right to cancel such transactions, as well as the results of services provided by the Company based on such transactions. The Funds debited as a result from the Account of the Client will be refunded by the Company to the Account of the Client when and if an internal investigation reveals any technical errors and the Company has access to such funds.</p>
        <p>5.18. The Company has the right to impose a limit on the Withdrawal of Funds equal to the sum of the Client's Deposits for the last 30 (Thirty) days.</p>
        <p>5.19. In cases where the Company's Security Service suspects the Client of fraud or deception, the Company has the right to block the Client's Account without prior notice and without the possibility of Account crediting and Withdrawing Funds for the period up to 10 (Ten) business days. Upon results of the Company's Security Service investigation, Company has the right to block the Client's Account permanently and deduct the amount of actual damage caused by the actions of the Client to the Company, as well as the profits that the Client received as a result of the fraud or deception, from the Client's Account.</p>
        <p>5.20. Refund Policy</p>
        <p>5.20.1. All refunds shall be made through the Non-trading Operations as described in Section 5 of this Agreement.</p>
        <p>5.20.2. If the Client deposits funds into their Account using a bank card, they also may request a refund via support@quarax.com. Such refund could not be made unless and until all of the following conditions have been fulfilled:</p>
        <p>1) there are enough funds on the Client Account for a refund;</p>
        <p>2) there are no active Bonuses on the Client Account.</p>
        <p>5.20.3. In addition, the Company has the right to refund the payment without notifying the Client if, in the opinion of the Company, the operation has signs of fraud.</p>
        <p>6. Quotes</p>
        <p>6.1. The Client acknowledges that when using the Company's services, the only reliable source of information about Quote streams is the Company Server. Quotes displayed on the Trading Platform cannot serve as a reliable source of information on Quotes streams, since in the case of an unstable connection between the Trading Platform and the Server, some Quotes from the streams may not reach the Trading Platform.</p>
        <p>6.2. The charts displayed on the Trading Platform are of an indicative nature. The Company does not guarantee that a Trading Operation will be conducted according to the Quote displayed on the chart on the Trading Platform at the time the Client submits the Trading Order.</p>
        <p>6.3. The Asset Quotation on the Trading Platform is determined by the formula: (purchase+sale)/2.</p>
        <p>6.4. If a Client’s Trading Order is executed on a non-market Quote, the Company corrects the financial result of the Trade in accordance with the market Quotes at the time of execution of that Trading Order or cancels the result of the Trade.</p>
        <p>7. Procedure for Conducting Trading Operations</p>
        <p>7.1. The processing of a Client’s Trading Orders takes place in the following order:</p>
        <p>7.1.1. The Client draws up a Trading Order, which is then tested for correctness on the Trading Platform.</p>
        <p>7.1.2. From the Trading Platform, the Client’s Trading Order is transmitted to the Server, where it is retested.</p>
        <p>7.1.3. After being retested, the Trading Order is processed on the Server, and the result of the processing is transmitted to the Trading Platform.</p>
        <p>7.2. The processing time of a Client's Trading Order depends on the quality of communication between the Trading Platform and the Server, as well as on the market conditions. Under normal market conditions, the processing time of a Client’s Trading Order is usually 0-4 seconds. Under market conditions other than normal, the processing time of a Client’s Trading Order may be extended.</p>
        <p>7.3. Opening Trades</p>
        <p>7.3.1. The minimum amount of Client investment in one Trade on the Trading Platform is $1/€1 or an amount equivalent to $1 (depending on the Account currency); the maximum amount is $1,000/€1,000 or an amount equivalent to $1,000 (depending on the Account currency).</p>
        <p>7.3.2. A Client’s Trading Order to open a Trade will be rejected for the following reasons:</p>
        <p>- the Client submits the Trading Order before the first Quote of the Trade Asset is received on the Trading Platform at the opening of the market; &nbsp;and/or</p>
        <p>- there are not enough available funds in the Client’s Account to open a new Trade.</p>
        <p>7.3.3. A Client’s Trading Order to open a Trade may also be rejected by the Server under market conditions other than normal.</p>
        <p>7.3.4. A Client’s Trading Order to open a Trade is considered executed, and the Trade open, after a corresponding record appears in the Log File. Each Trade on the Server is assigned a unique identification number.</p>
        <p>7.4. Closing Trades</p>
        <p>7.4.1. The closing of the Trade occurs at the current Quotation of the Trade Asset that is on the Server at the time of the closing of the Trade.</p>
        <p>7.4.2. A Client’s Trading Order to close a Trade is considered completed, and the Trade closed, after a corresponding record appears in the Log File.</p>
        <p>7.5. The Company has the right to limit the maximum number of Trades made by a Client in one minute, hour, or calendar day.</p>
        <p>7.6. The Company has the right to change the percentage of profitability, the size of the minimum and maximum amounts of Client investment in one Trade, as well as the Expiration periods for one, multiple, or all Assets.</p>
        <p>7.7. Malfunctions and/or failures in the operation of computer equipment and/or software of the Company, unstable Internet connections, interruptions in the transmission of information streams, interruptions in power supply, malfunctions in the operation of exchanges, hacker attacks, as well as any illegal actions in regard to equipment and/or the Company Server, force majeure circumstances, and the suspension of trading on financial markets, which affect the Assets available on the Website are direct grounds for the invalidation of Trades executed under those circumstances.</p>
        <p>8. Bonuses and gifts, participation in Tournaments and promotions</p>
        <p>8.1. Bonuses are credited to the Client's Account in accordance with bonus or promotional programs conducted by the Company.</p>
        <p>8.2. The amount of a Bonus depends on the conditions of the promotion or program for which it was credited (non-deposit Bonuses), and/or the size of the Client's Deposit (deposit Bonuses).</p>
        <p>8.3. Bonuses credited to the Account are not a financial obligation of the Company to the Client.</p>
        <p>8.4. After a Bonus has been activated, the funds in the Client's Account become available for Withdrawal only after the Client completes the Mandatory Trading Turnover.</p>
        <p>Mandatory trading turnover is the Bonus amount multiplied by its leverage factor. If the leverage factor of a Bonus is not specified, the leverage factor should be considered equal to 40 for non-deposit Bonuses and for deposit Bonuses that are 50% or more of the amount of the Deposit made when using the Bonus, and 35 for deposit Bonuses that are less than 50% of the amount of the Deposit made when using the Bonus. The amount of the Client's investment in the Trade taken into account in the Mandatory Trading Turnover is directly proportional to the profitability of the Asset of that Trade.</p>
        <p>8.5. Zero-result Trades in the FTT Trading Mechanics are not included in the Mandatory Trading Turnover.</p>
        <p>8.6. Within the framework of a single promotion, the Client is entitled to receive Bonus funds only once, unless otherwise specified in the conditions of the promotion.</p>
        <p>8.7. The profit received by the Client for Trades using Bonuses may have limitations on the amount of Withdrawal.</p>
        <p>8.8. Gift non-deposit Bonuses must be activated in the Client’s Personal Account within 3 (Three) days from the moment they are credited.</p>
        <p>8.9. After a Bonus is activated, the Client has the right to cancel it by contacting the Company's Client Support Service using the contacts specified in section 12 of this Agreement. Declining or canceling a Bonus is possible only if the Client has completed no Trading Operations since the Bonus was credited.</p>
        <p>8.10. Upon the expiration of a promotion, the Bonus credited according to that promotion may be debited from the Client's Account.</p>
        <p>8.11. A Client can have only one active Bonus in their Account. If the Client already has an active Bonus in their Account, they cannot activate another one until the Mandatory Trading Turnover for the active Bonus has been completed.</p>
        <p>8.12. If the Client's Account Balance falls below the minimum allowable amount of Client investment in a Trade, the Bonus is reset.</p>
        <p>8.13. Bonuses cannot be used in Tournaments.</p>
        <p>8.14. Participation in Tournaments. The Client uses a special tournament account to participate in Tournaments. Trades in a Tournament are made in virtual currency (₮). All participants have the same starting tournament balance at the start of the Tournament. The main goal of the participants is to have the highest tournament balance by the time the Tournament ends. The prize fund is distributed among the winners who have won prize places. Detailed conditions for participation in a Tournament can be found on the page corresponding to such Tournament on the Company's Website.</p>
        <p>8.15. The Client has the right to participate in all available Tournaments and promotions held by the Company. Clients must independently familiarize themselves with the conditions of such Tournaments and promotions posted on the Company's Website.</p>
        <p>8.16. The monetary funds received by the Client from the Company as a prize for participation in a Tournament are credited to their real Account after the prize is activated in the Client’s Personal Account, unless otherwise specified in the tournament conditions.</p>
        <p>8.17. If the Security Service of the Company suspects a Client of fraudulent actions in order to win a Tournament or promotion, the Company has the right to review or rescind the Client’s results in that Tournament or promotion, and also to ban them from participating in subsequent Tournaments and/or promotions. In the event that the fact of fraud is confirmed, the results of the Client in that Tournament or promotion are rescinded.</p>
        <p>8.18. As part of promotions or special programs, the Company may provide additional gifts to the Client. Types and the amount of such gifts depend on the conditions of the promotion or program.</p>
        <p>9. Client risks</p>
        <p>9.1. The Client fully acknowledges the following:</p>
        <p>- the conducting of Trading operations with financial instruments is accompanied by significant risks. Before using the Company's services, the Client needs to analyze their financial capabilities;</p>
        <p>- the Trading Operations they carry out through the Trading Platform are not Trades concluded on an official exchange. They are over the counter, and therefore carry a greater risk for the Client than official exchange Trades;</p>
        <p>- any information and/or recommendations they receive on the Website from representatives or partners of the Company are not considered a direct offer to conduct a Trading Operation or a financial transaction;</p>
        <p>- they may incur financial losses as a result of malfunctions and/or failures in the operation of computer equipment, software, an unstable internet connection, power outages, or other technical factors;</p>
        <p>- in market conditions other than normal, the processing time of their Trading Orders may be extended, as a result of which the Client may incur losses. In addition, sharp fluctuations in Quotes may result in Client losses when a Trade is executed at a Quote Price that is different from the Quote Price displayed on the Trading Platform.</p>
        <p>9.2. In some countries, use of the Company's services may be restricted or prohibited by law. The Client assumes all risks associated with analysis of the legislation of their country, or their country of residence, for such restrictions or prohibitions, as well as responsibility for using the services of the Company in countries where they are restricted or prohibited.</p>
        <p>9.3. The Client acknowledges that the Company does not guarantee receipt by the Client of profit in any amount or the absence of losses in the course of the Client using the services.</p>
        <p>10. Guarantees and liability. Force majeure</p>
        <p>10.1. The Company is not a credit institution, does not conduct banking activities, does not attract monetary funds from individuals for the purpose of investing it with interest over a certain time period, and does not open or maintain bank accounts.</p>
        <p>10.2. The Company does not provide its services in the following territories or to citizens and/or residents of the following countries (territories): North Korea, Canada, USA, Australia, Austria, Belgium, Brazil, Bulgaria, Croatia, Czech Republic, Denmark, Estonia, Finland, France, Greece, Hungary, Ireland, Italy, Germany, Latvia, Lithuania, Luxembourg, Malta, the Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Norway, Iceland, Liechtenstein, Sweden, United Kingdom, Andorra, Vatican, Monaco, San Marino, Cyprus, Switzerland, Israel, Syria, Singapore, Hong Kong, New Zealand, Iran, Saint Vincent and the Grenadines, Moldova, Japan, Russia, Belarus, Afghanistan, Iraq, Libya, Palestine, South Sudan, Albania, Haiti, Jamaica, Mali, Myanmar, Nicaragua, Senegal, Zimbabwe, Cuba, United Arab Emirates, in cases when it is contrary to the current legislation of those countries and/or the Company's internal policy.</p>
        <p>10.3. The Client guarantees the following when using the services of the Company:</p>
        <p>- they conclude Trades exclusively in their own name and in their interest;</p>
        <p>- they are not a citizen and/or resident of a country in which the Company does not render its services.</p>
        <p>10.4. The Client is responsible for the authenticity and validity of the documents presented by them during verification. In the event that during the verification process, the Client provides inaccurate information, falsified or invalid documents, the Company has the right to refuse to service the Client's Account, without granting the right to Withdraw profits, as well as to withhold the Client’s monetary funds in the amount of actual damage caused to the Company through their actions. The Company has the right to refuse to re-register that Client.</p>
        <p>10.5. Within the framework of compliance with international AML legislation, when registering on the Trading Platform, the Client ensures that the monetary funds deposited by them into the Account have not been obtained illegally and are not the result of drug trafficking, kidnapping, or other criminal or illegal activities. The Client undertakes not to use the Website for the purpose of legalizing proceeds from crime or for other illegal activities. The Company reserves the right to refuse to let the Client use their Account, to block, cancel, or close the Account, and to withhold funds in the Client's Account if the Client does not adhere to or does not comply with the requirements and principles of AML legislation. If the Company suspects the Client of conducting illegal or unlawful activities through their Account, the Company reserves the right to disclose all information relating to the Client to the competent authorities, as well as to block and/or close the Client's Account and/or withhold the funds in the Client's Account. If the origin of the Client’s funds available on the Account is demonstrated to be legal, the Company will return such withheld funds unless there are any government acts prohibiting such return.</p>
        <p>10.6. The Client undertakes to provide documents and carry out other necessary actions (at the discretion of the Company) aimed at compliance with AML international legislation.</p>
        <p>10.7. The Client is fully aware that actions performed by them and/or by third parties with their participation that could destabilize the operation of the Website, the equipment, services, software and/or hardware, or the Company's operation in general, will entail a direct refusal of the Company to service the Client’s Account, without granting the right to Withdraw profits, as well as the withholding of the Client's monetary funds in the amount of actual damage caused to the Company through their actions. The Company has the right to refuse to re-register that Client.</p>
        <p>10.8. The Client is personally responsible for the login and password used to access their Account on the Website. The Client is obliged to prevent any third party from accessing their Account on the Website. In the event of unauthorized access to the login and password and/or the Client's Account, they are obliged to immediately notify the Company. The risks and losses of the Client associated with the process of restoring their access to the Account do not lead to additional obligations for the Company, apart from providing new data for the Client’s access to their Account after they complete an additional procedure to identify them as the holder of the Account. The Company is not obliged to compensate for any losses or pay any profits to the Client resulting from unauthorized access to the Client's Account.</p>
        <p>10.9. The Company shall not be liable for any actions or inaction of the Client in the course of using its services, as well as for the Client's losses resulting from the concluding of Trades by the Client using the Trading Platform.</p>
        <p>10.10. The Company shall not be liable for failing to fulfill its obligations, including the Client’s losses, which arise as a result of hacker attacks, computer equipment malfunctions (to both the Client and the Company), or data transmission via communication channels that occurred through no fault of the Company.</p>
        <p>10.11. The Company shall not be liable for the Client's losses arising from force majeure circumstances. Force majeure circumstances include without limitation the following: natural disasters, man-made disasters, military actions, terrorist acts, uprisings, civil unrest, strikes, riots, the introduction of government restrictions affecting the fulfilling of this Agreement, the introduction of (or changes to) market and/or currency rules, and the suspension of exchange trading.</p>
        <p>10.12. If during the conducting of Trading Operations on the Website, the Client makes a profit using artificial intelligence, specialized software, so-called “bots,” or vulnerabilities in stock exchange software or the Company Server, such profits are not the Company's financial responsibility and are not paid to the Client.</p>
        <p>10.13. In the event that the Client violates the terms of this Agreement, the Company has the right to terminate this Agreement unilaterally without prior notification of the Client. In this case, the balance of the Client’s Account may be transferred by using payment details provided during the registration, and the Company will deduct from the Client’s Account any amount of i) actual damages suffered by the Company through any act of the Client, and ii) profits generated by the Client through violations of this Agreement. The Company has the right to refuse to re-register that Client.</p>
        <p>11. Complaints and dispute resolution</p>
        <p>11.1. In the event of a dispute, the Client first must contact the Company's Client Support Service using the contacts specified in section 12 of this Agreement. If the Client deems the answer given by the Support Service to be unsatisfactory or the Support Service does not have the authority to resolve the question raised by the Client, the Client has the right to contact the Support Service with a request to forward the question to the Company’s Dispute Resolution Department or to send the complaint via email to complaints@quarax.com.</p>
        <p>11.2. When submitting a complaint, the Client must indicate the following information:</p>
        <p>- the Client's first and last name;</p>
        <p>- the Client's email address;</p>
        <p>- when (date) and which operations were involved when the dispute arose or was detected;</p>
        <p>- a detailed description of the situation;</p>
        <p>- attached files confirming the dispute (if any).</p>
        <p>In order for the dispute to be resolved as soon as possible, the Client must provide all the above information in full.</p>
        <p>11.3. In the event of non-compliance of the complaint with the requirements set out in clauses 11.1 and 11.2 of this Agreement, and/or if any of the following conditions exist,</p>
        <p>- in the complaint, the Client makes provocative statements, unfounded accusations, or threats of “denigrating” the business image of the Company;</p>
        <p>- the received message contains threats, insults, or vocabulary of an obscene nature aimed at the Company and/or its employees;</p>
        <p>сonsideration of the Client's complaint may be rejected.</p>
        <p>The Company recognizes such actions as unacceptable and has the right to appeal against them to the competent authorities.</p>
        <p>11.4. When considering a Client's complaint, the Company is always guided by their interests and is obliged to give a preliminary response within 2 (Two) business days from the day the complaint is received, containing the following information:</p>
        <p>- confirmation of receipt of the complaint by the Dispute Resolution Department;</p>
        <p>- preliminary results of the audit or information that may be relevant to the subject of the complaint;</p>
        <p>- a deadline for making a decision regarding the complaint.</p>
        <p>11.5. Within 10 (Ten) business days from the day following the date of the complaint, the Company provides the Client with an answer about the measures taken to resolve the dispute, as well as recommendations for further actions by the Client. If the Company needs to obtain additional information to settle the dispute, it is entitled to extend the time for consideration of the complaint, but for no more than 10 (Ten) business days, and it is obliged to notify the Client.</p>
        <p>11.6. Complaints about the recovery of lost profits and/or compensation for moral damage by the Company are not accepted for consideration.</p>
        <p>11.7. A dispute is deemed to be settled if within 5 (Five) business days from the moment a response is sent to the Client, the answer is not appealed by them.</p>
        <p>11.8. If the dispute between the Client and the Company has not been resolved within 1 (One) month from the date of filing the complaint, within 15 (Fifteen) days from the end of that period, the Client has the right to apply to the <a href="https://financialcommission.org/">Financial Commission</a> or to an authorized court under Saint Vincent and the Grenadines law to resolve the dispute.</p>
        <p>12. Contacts</p>
        <p>12.1. To contact the Company, the Client may use the following methods:</p>
        <p>- to the email address: support@quarax.com;</p>
        <p>- via online chat on the Website.</p>
        <p>12.2. The Client’s contacts are their email address, indicated when registering on the Website, as well as the phone number indicated in their Personal Account on the Company Website if the Client wishes to indicate it.</p>
        <p>12.3. The Company is not responsible for incorrect indication by the Client of their contact information on the Website.</p>
        <p>13. Taxes</p>
        <p>The Company is not a tax agent and does not provide data on the operations of its Clients to third parties. Such information can only be provided if an official request is made by a competent national authority.</p>
        <p>14. Validity, amendment, and termination of this Agreement</p>
        <p>14.1. This Agreement becomes legally binding at the time of the Client’s registration on the Website.</p>
        <p>14.2. The obligations and rights of the Client and the Company established by this Agreement are considered a long-term act and are valid until the termination of the Agreement.</p>
        <p>14.3. The Company has the discretion at any time to make amendments to this Agreement. If amendments are made to the Agreement, they will come into force from the moment the amended text of the Agreement is posted on the Website, unless a different term for is specified for the amendments to come into force. The Client is obliged to independently familiarize themselves with the current version of the Agreement posted on the Website.</p>
        <p>14.4. If the Client does not agree to the amended version of the Agreement, they must stop using the Company's services and block their Account via the Personal Account interface on the Website or by contacting the Company's Client Support Service using the contacts specified in section 12 of this Agreement, after first making a Withdrawal of Funds from their account.</p>
        <p>14.5. This Agreement may be terminated as follows:</p>
        <p>- at the initiative of any Party;</p>
        <p>- in the case of death of the Client or recognition of their legal incapacity;</p>
        <p>- in the case of liquidation of the Company.</p>
        <p>14.6. Regardless of the basis for termination of the Agreement, the Company undertakes to fulfill its obligations to the Client in the manner provided for in this Agreement.</p>
        <p>14.7. The Client has the right to terminate this Agreement at any time, regardless of their motives.</p>
        <p>14.8. To terminate this Agreement unilaterally, the Client must block their Account via the Personal Account interface on the Website or by contacting the Company's Client Support Service using the contacts specified in section 12 of this Agreement, after first making a Withdrawal of Funds from their Account. If the Client fails to Withdraw their Funds independently, the Company may transfer the balance of the Account by using payment details provided by the Client during registration.</p>
        <p>14.9. If at the request of the Client, the Company removes the block on their Account, this Agreement resumes its effect according to the version valid at the time of the unblocking.</p>
        <p>14.10. The Company has the right to terminate this Agreement unilaterally without providing reasons.</p>
        <p>14.11. In the event of termination of its activities, the Company is obliged to notify the Client about this no later than 1 (One) calendar month prior to the termination of its activities.</p>
        <p>14.12. In the event of termination of its activities, the Company is obliged to pay the Client the funds in their Account at the time of the termination of the Company's activities, in full.</p>
        <p>15. Final provisions</p>
        <p>15.1. The Client does not have the right to fully or partially transfer their rights and obligations under this Agreement to a third party.</p>
        <p>15.2. In the case of a discrepancy between the text of this Agreement in English and the text in other languages, the version of the Agreement in English shall prevail.</p>
        <p>15.3. This Agreement is governed by the laws of Saint Vincent and the Grenadines. Any dispute arising out of or in connection with this Agreement, including any question regarding its existence, validity, or termination, shall be submitted and finally resolved by the court in accordance with the laws of Saint Vincent and the Grenadines.</p>
        <p>Effective August 1, 2023</p><br />
      </div>
    </div>
  )
}